name: Recaf4Forge Release

on:
  push:
    branches: [master]

jobs:
  validation:
    name: "Post build - Validation"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.3

  build:
    needs: validation
    runs-on: ubuntu-latest
    env:
      PROPERTIES_PATH: gradle.properties
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Step 1 - Setup JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 8
        java-package: jdk+fx

    - name: Step 2 - Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Step 3 - Build with Gradle
      run: ./gradlew build

    - name: Step 4 - Read version
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: ${{ env.PROPERTIES_PATH }}
        property: version

    - name: Step 6 - Create a Release
      uses: 1fxe/GitHub-Release-Action@main
      with:
        release_token: ${{ secrets.RELEASE_TOKEN }}
        release_tag: v${{ steps.read_property.outputs.value }}
        release_title: Recaf4Forge-${{ steps.read_property.outputs.value }}
        release_file: build/libs/Recaf4Forge-${{ steps.read_property.outputs.value }}.jar

